### ISSUE TITLE
Detatched head prevents commit of custom CSS stylesheets and JS files to repository

### ISSUE THREAD

**Issue by Dodesimo** [The-Zombie-Fridge-Journal/zfjournal_source#2]
Because the theme has been added to this repository via a GitHub submodule, after a git pull, and an attempt to commit and push, a "detached head" warning appears. This is because the theme repository has to be _forked_ before it can be added as submodule (without a fork we are not owners of the theme repository and are therefore unable to add custom CSS stylesheets and JS files).

**Comment by Dodesimo** [comment]
First step to solving issue has been done: creating a GitHub repo fork of the theme repository: https://github.com/The-Zombie-Fridge-Journal/hugo-theme-novela

**Comment by akirarorschach** [comment]
Here is a reference guide on how to add a Hugo theme as a submodule and be able to edit it: [https://www.andrewhoog.com/post/git-submodule-for-hugo-themes/](url).

**Comment by akirarorschach** [comment]
I have updated the `.gitmodules` file to use the ZFJ fork of the Hugo Novela theme as the theme submodule instead of the original theme repository. See the following commit: [https://github.com/The-Zombie-Fridge-Journal/zfjournal_source/commit/2416f30f39908dac95b47b8c0b319d6c0a26f92d](https://github.com/The-Zombie-Fridge-Journal/zfjournal_source/commit/2416f30f39908dac95b47b8c0b319d6c0a26f92d).

**Comment by Dodesimo** [comment]
I followed the instructions in this tutorial (https://www.banjocode.com/post/hugo/custom-css/) and committed all relevant files, yet a build error occurs. Not sure why: https://github.com/The-Zombie-Fridge-Journal/zfjournal_source

**Comment by akirarorschach** [comment]
Your commit changed the submodule again, which I don't think was supposed to happen, so I reverted that. The respective files are not present in the theme submodule's [`static`](https://github.com/The-Zombie-Fridge-Journal/hugo-theme-novela/tree/master/static) folder. 

I followed step 3 of the Banjo Code tutorial (hereinafter referred to as "the tutorial) and updated the  [`head.html`](https://github.com/The-Zombie-Fridge-Journal/hugo-theme-novela/blob/master/layouts/partials/head/head.html) file. Refer to commit [`311131a`](https://github.com/The-Zombie-Fridge-Journal/hugo-theme-novela/commit/311131ac747c06254ed21b7d3e0849db231b48e0) for that. 

I then followed step 4 of the tutorial and added the custom CSS and JS files to the static folder. Refer to commits [`7e455a7`](https://github.com/The-Zombie-Fridge-Journal/hugo-theme-novela/commit/7e455a7ec734b5267984c268b9311ccaf2b1a264) and [`9827097`](https://github.com/The-Zombie-Fridge-Journal/hugo-theme-novela/commit/982709747eaa6a2a225f82bc22e2ab41fdd0cfd2). 

Please verify that everything works now and update the issue accordingly.

**Comment by akirarorschach** [comment]
This issue concerns the commit of the custom CSS and JS files. As the files have been added, I will close the issue.
