### ISSUE TITLE
Rename "articles" and "article" folders within partials

### ISSUE THREAD

**Issue by akirarorschach** [The-Zombie-Fridge-Journal/zfjournal_source#5]
**DESCRIPTION** 

For some reason, within [layouts/partials](https://github.com/The-Zombie-Fridge-Journal/website_theme/tree/master/layouts/partials), there are two folders for partials, with one named `articles` and the other name `article`. This similarity is confusing. Dunno why the theme creators made the two folders so similar. 

**POSSIBLE SOLUTIONS** 

- [ ] figure out what the partials in each folder do 
- [ ] rename the folders appropriately 
- [ ] update the paths in the files that need the paths updated 

**REFERENCES**

- [https://github.com/The-Zombie-Fridge-Journal/website_theme/tree/master/layouts/partials/articles](https://github.com/The-Zombie-Fridge-Journal/website_theme/tree/master/layouts/partials/articles)
- [https://github.com/The-Zombie-Fridge-Journal/website_theme/tree/master/layouts/partials/article](https://github.com/The-Zombie-Fridge-Journal/website_theme/tree/master/layouts/partials/article)

**Comment by Dodesimo** [comment]
So the two different folders are for two **different types of pages.**

The "articles" partials folder represents partials for the webpage showing **all the articles published.**

The "article" partials folder represents **common partials each article webpage** has. 

As a result, I do not think anything needs to be renamed. There was a reason behind why they were named so similarly.
