### ISSUE TITLE
Rename several "hero.html" files

### ISSUE THREAD

**Issue by akirarorschach** [The-Zombie-Fridge-Journal/zfjournal_source#6]
**DESCRIPTION** 

There are multiple files named `hero.html` in the website_theme partials folder, which is confusing. These need to be renamed appropriately to properly differentiate between them. Wonder why they were even named "hero" in the first place as opposed to something like "header." 

**POSSIBLE SOLUTIONS** 

- [x] figure out what the respective `hero.html` files do
- [ ] rename them appropriately 
- [ ] update the files that use the respective `hero.html` files

**REFERENCES**

Here are the `hero.html` files that I have been able to identify:
- [articles/hero.html](https://github.com/The-Zombie-Fridge-Journal/website_theme/blob/master/layouts/partials/articles/hero.html)
- [page/hero.html](https://github.com/The-Zombie-Fridge-Journal/website_theme/blob/master/layouts/partials/page/hero.html)
- [article/hero.html](https://github.com/The-Zombie-Fridge-Journal/website_theme/blob/master/layouts/partials/article/hero.html)
- [author/hero.html](https://github.com/The-Zombie-Fridge-Journal/website_theme/blob/master/layouts/partials/author/hero.html)

**Comment by Dodesimo** [comment]
So from web development, a "hero" is a dynamic banner. It's essentially the large image that is at the top of a website. For example, using the Team Faraday website, the hero banner is the large red section in the middle of the snip below:

![image](https://user-images.githubusercontent.com/29319604/140633792-2d343f1b-41af-4779-8416-3f7627aa9a4a.png)

For each subcategory of webpage in the site (articles, pages, article, and authors), there's a hero banner associated, which is essentially controlled with the HTML file. 

In terms of renaming the files, we would want to see **instances of where the files are referenced in other HTML, YML, CSS, and/or JS files in the theme. **

Attached is a website explaining what a "hero" is: https://yourstory.com/2017/03/what-is-hero-image/amp

**Comment by akirarorschach** [comment]
After review, I no longer think it's necessary to rename the `hero.html` files because the additional part of the path given makes it clear what `hero.html` file is being used.
