### ISSUE TITLE
Create various pages for development

### ISSUE THREAD

**Issue by akirarorschach** [The-Zombie-Fridge-Journal/zfjournal_source#7]
**DESCRIPTION** 
We got the site foundation set up. Now let's tinker around with it. 

**OBJECTIVE** 
To mess around with the site theme and see the results of said messing around, let's create some pages to mess around with. 

- `Foreign Affairs` (division, largest category) 
- `United Kingdom` (subdivision) 
- `UK Government`, `UK Politics` (article tags) 
- example article under `Foreign Affairs - United Kingdom` with tag `UK Government`

These are some example names of pages to demonstrate the organisation of ZFJ articles. 

**POSSIBLE SOLUTIONS** 

- [x] create test division page 
- [x] create test subdivision page 
- [x] create test tag pages 
- [x] create test article page 

**REFERENCES**
refer to the ZFJ website structure document for notes on website and content organisation (access restricted to ZFJ staff): [https://docs.google.com/document/d/11w1NGABef_YYhUFn9-yldK5o_JjsVacaTU-qtp_MaXM/edit](https://docs.google.com/document/d/11w1NGABef_YYhUFn9-yldK5o_JjsVacaTU-qtp_MaXM/edit)

**Comment by Dodesimo** [comment]
In regards to formatting for the test page (large gap between text and title), try using this CSS documentation to change "```style = "position:relative;"```:
https://www.w3schools.com/cssref/pr_class_position.asp

**Comment by akirarorschach** [comment]
The test pages have been created. They are located in [https://github.com/The-Zombie-Fridge-Journal/zfjournal_source/tree/main/content/test%20folder](https://github.com/The-Zombie-Fridge-Journal/zfjournal_source/tree/main/content/test%20folder) and are ready for development.
